# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Home
  #   url: /
  #   weight: 1
  - name: Profile
    url: /author/김채현/
    weight: 100

  - name: Project
    url: project
    weight: 200

  - name: Plans
    url: post
    weight: 300
  - parent: Plans
    name: futurity
    url: publication
    weight: 310
  - parent: Plans
    name: interview
    url: interview
    weight: 320

  - name: Information
    url: event
    weight: 400
    
  - name: Contact
    url: contact
    weight: 500
